title: "Souvik Bag's Personal Webpage"
logo: profile.jpeg
description: "Ph.D. Student in Statistics | Machine Learning Enthusiast"
theme: jekyll-theme-minimal
baseurl: "" # Make sure this is empty for a personal website

