###########################################################
### Welcome to Beautiful Jekyll!
### This config file is meant for settings that affect your entire website. When you first
### set up your website you should go through all these settings and edit them, but after
### the initial set up you won't need to come back to this file often.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: Souvik Bag

# Your name to show in the footer
author: Souvik Bag

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Publications: "publications"
  Contact: "contact"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "profile.jpeg"

# By default, the image is cut into a circle. You can disable this behavior by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: "profile.jpeg"

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "sbk29@missouri.edu"
  linkedin: "souvikbag"
  google-scholar: "mJQ9QmgAAAAJ"

###########################
# --- General options --- #
###########################

# Add a search button to the navbar
post_search: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to your website in the footer
url-pretty: "MyWebsite.com"

# Add the website title to the title of every page
title-on-all-pages: true

# Colours / background image
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

####################
# --- Comments --- #
####################

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname
#disqus: ""

# To use Utterances comments
#utterances:
#  repository: "souvikbag/personal-website"

################
# --- Misc --- #
################

# Output options (more information on Jekyll's site)
timezone: "America/Chicago"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
